mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.CARGOS.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.CARGOS.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.CONTRATOS.DN.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.CONTRATOS.DN.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.EMPRESAS.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.EMPRESAS.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.ESTABELECIMENTOS.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.ESTABELECIMENTOS.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.ESTABELECIMENTOS.DR.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.ESTABELECIMENTOS.DN.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.FUNCIONARIOS.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.FUNCIONARIOS.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.EXAMES.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.EXAMES.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.FOL.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.FOL.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.GHE.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.GHE.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.LISTADR.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.LISTADR.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.MEDICOS.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.MEDICOS.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""

mqsicreateconfigurableservice IN_DEV01 -c SecurityProfiles -o GS.ACE.DEV.OMNI.PRESTADORES.GET -n mapping,rejectBlankpassword,propagation,passwordValue,keyStore,authorizationConfig,authenticationConfig,idToPropagateToTransport,trustStore,authentication,authorization,mappingConfig,transportPropagationConfig -v "NONE","TRUE","TRUE","PLAIN","Reserved for futureuse",\"ldap://fiepr.local:389/|(CN=GS.ACE.DEV,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)(CN=GS.ACE.DEV.OMNI.PRESTADORES.GET,OU=OMNI,OU=Desenvolvimento,OU=IBM-IIB,OU=SEGURANCA,OU=GRUPOS,OU=TAXONOMIA,DC=fiepr,DC=local)\",\"ldap://fiepr.local:389/dc=fiepr,dc=local?sAMAccountName\","Message ID","Reserved for future use","LDAP","LDAP","",""