USE [BROKER]
GO

/****** Object:  Table [dbo].[SGT_TIPO_PROCESSO]    Script Date: 22/10/2024 08:49:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SGT_TIPO_PROCESSO](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome_tipo_processo] [varchar] (100) NULL,
 CONSTRAINT [PK_SGT_TIPO_PROCESSO_ID] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


