USE [BROKER]
GO

/****** Object:  Table [dbo].[SGT_PRODUTO_ERROS]    Script Date: 22/10/2024 08:49:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SGT_PRODUTO_ERROS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_etapa] [int] NULL,
	[erro] [varchar](max) NOT NULL,
	[data] [datetime] NOT NULL,
	[local_transaction_id] [varchar](100) NULL,

 CONSTRAINT [PK_SGT_PRODUTO_ERROS_ID] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SGT_PRODUTO_ERROS]  WITH CHECK ADD  CONSTRAINT [FK_SGT_PRODUTO_ERROS_ID_ETAPA] FOREIGN KEY([id_etapa])
REFERENCES [dbo].[SGT_PRODUTO_ETAPAS] ([id])
GO

ALTER TABLE [dbo].[SGT_PRODUTO_ERROS] CHECK CONSTRAINT [FK_SGT_PRODUTO_ERROS_ID_ETAPA]
GO


