USE [BROKER]
GO

/****** Object:  Table [dbo].[SGT_NOME_ETAPAS]    Script Date: 22/10/2024 08:49:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SGT_NOME_ETAPAS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_tipo_processo] int NULL,
	[nome_etapa] [varchar](100) NOT NULL,
	[obervacoes] [varchar](100) NULL
 CONSTRAINT [PK_SGT_NOME_ETAPAS_ID] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SGT_NOME_ETAPAS]  WITH CHECK ADD  CONSTRAINT [FK_SGT_NOME_ETAPAS_ID_TIPO_PROCESSO] FOREIGN KEY([id_tipo_processo])
REFERENCES [dbo].[SGT_TIPO_PROCESSO] ([id])
GO

ALTER TABLE [dbo].[SGT_NOME_ETAPAS] CHECK CONSTRAINT [FK_SGT_NOME_ETAPAS_ID_TIPO_PROCESSO]
GO


